apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api
  namespace: payments-api-dev
  labels:
    app: payments-api
    env: dev
    managed-by: huaira
    team: cloud-army
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-api
  template:
    metadata:
      labels:
        app: payments-api
        env: dev
        team: cloud-army
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: app
        image: ghcr.io/cloud-army/payments-api:sha-1cc92d6e
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ENV
          value: dev
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: payments-api
  namespace: payments-api-dev
  labels:
    app: payments-api
    team: cloud-army
spec:
  selector:
    app: payments-api
  ports:
  - name: http
    port: 80
    targetPort: 8080
