name: CI - Build and Push to Harbor

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-push:
    runs-on: [self-hosted, huaira]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install crane
        run: |
          curl -sL https://github.com/google/go-containerregistry/releases/download/v0.20.2/go-containerregistry_Linux_arm64.tar.gz \
            | tar -xz -C /usr/local/bin crane
          crane version

      - name: Build image
        run: |
          SHORT_SHA=${GITHUB_SHA::8}
          docker build \
            -t payments-api:${SHORT_SHA} \
            -t payments-api:latest .

      - name: Push to Harbor via crane
        run: |
          SHORT_SHA=${GITHUB_SHA::8}
          REGISTRY=harbor.harbor.svc.cluster.local
          docker save payments-api:${SHORT_SHA} | \
            crane push --insecure --platform linux/arm64 \
              -u admin -p Harbor12345 \
              - ${REGISTRY}/library/payments-api:${SHORT_SHA}
          docker save payments-api:latest | \
            crane push --insecure --platform linux/arm64 \
              -u admin -p Harbor12345 \
              - ${REGISTRY}/library/payments-api:latest
